{% set name = "pyexcel-xlsx" %}
{% set version = "0.6.1" %}
{% set sha256 = "80b7985d394b73abf5c52212027bbbc0c7f6090192bcbc76403f8672d74c7960" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}
    - openpyxl >=2.6.1
    - pyexcel-io >=0.6.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyexcel_xlsx

about:
  home: https://github.com/pyexcel/pyexcel-xlsx
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A wrapper library to read, manipulate and write data in xlsx and xlsm format using openpyxl
  description: |
    'A wrapper library to read, manipulate and write data in xlsx and xlsm ' +
    'format' +
    ''
  doc_url: http://pyexcel-xlsx.readthedocs.io/en/latest/
  dev_url: https://github.com/pyexcel/pyexcel-xlsx

extra:
  recipe-maintainers:
    - williamjamir
    - nicoddemus
